"""empty message

Revision ID: 9f9aedb14057
Revises: a08b801bfdb9
Create Date: 2022-08-10 18:59:47.948820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9aedb14057'
down_revision = 'a08b801bfdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.alter_column('Venue', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Venue', 'genres')
    op.alter_column('Artist', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
